sudo: false
notifications:
  slack:
    secure: OvkwWFNZXlD9CkUZBMdhiMGERlHeImEcWpCUp0vk/Z8pS7iM3PjrWYF7iZtt1La6z9LrQXh15OhI1jn6VN8IzMeZmrJYv3cgAJiCUnRkOu2iQjW6MKsZNl9gccdxfUr7r5wrV3th+48d353T7W2WEd6ADJSeI5jKu37STwIjztM=

# language: python
language: c
# We're not Python 2.6 compatible at the moment
# python: "2.7"
addons:
  apt:
    packages:
        - build-essential
        - python-dev
        - git
        - mercurial
        - python-pip
        - libopenmpi-dev
        - openmpi-bin
        - libblas-dev
        - liblapack-dev
        - gfortran
        - gmsh
        - python-tk
# Separate cache directories for OSX and Linux
cache:
  directories:
    - $HOME/cached_dependencies_$TRAVIS_OS_NAME
env:
  global:
    - CC=mpicc
    # The install script expects to see this environment variable
    - CACHE_DIRECTORY=$HOME/cached_dependencies_$TRAVIS_OS_NAME
    - FIREDRAKE_CI_TESTS=1
matrix:
  include:
    - os: osx
      # Only test a few things on OSX until we can cache some of the
      # build dependencies, otherwise we often get timeouts.
      env:
        TEST_FILES="tests/regression/test_identity.py"
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; brew install python; brew link --overwrite python ;  fi
  - pip install -U --user pip
  - pip install -U --user virtualenv
  # Fail fast on lint errors
  - pip install -U --user flake8 flake8-future-import
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH=$PATH:$HOME/Library/Python/2.7/bin; fi
  - make lint
install:
  - export CC=mpicc
  - mkdir tmp
  - cd tmp
  - ../scripts/firedrake-install --disable-ssh --minimal-petsc ${PACKAGE_MANAGER}
  - . ./firedrake/bin/activate
  # Having activated the virtualenv, attempt to save cached dependencies
  # This saves PETSc and petsc4py to speed up building
  - (cd firedrake; ../../scripts/firedrake-install --write-cache)
# command to run tests
script:
  - cd firedrake/src
  - (cd firedrake; make lint)
  - (cd firedrake; py.test firedrake -v ${TEST_FILES})
